# Generated by Django 5.2.7 on 2025-11-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0002_custombaseuser_is_staff'),
        ('ControlPanel', '0002_facedata'),
    ]

    operations = [
    ]
