# Generated by Django 5.2.7 on 2025-11-19 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0003_merge_0002_custombaseuser_is_staff_0002_facedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField(help_text='Tanınma güven skoru (0-1)')),
                ('camera_location', models.CharField(blank=True, help_text='Kamera konumu', max_length=100)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='access_snapshots/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='ControlPanel.customer')),
            ],
            options={
                'verbose_name': 'Geçiş Kaydı',
                'verbose_name_plural': 'Geçiş Kayıtları',
                'ordering': ['-entry_time'],
            },
        ),
    ]
